Document: holland
Title: Debian holland Manual
Author: <insert document author here>
Abstract: This manual describes what holland is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/holland/holland.sgml.gz

Format: postscript
Files: /usr/share/doc/holland/holland.ps.gz

Format: text
Files: /usr/share/doc/holland/holland.text.gz

Format: HTML
Index: /usr/share/doc/holland/html/index.html
Files: /usr/share/doc/holland/html/*.html
